-- Generated by Forgeable for the standalone backend API.
-- The remote table is created in the backend service, and this file keeps a Supabase-style SQL/RLS version inside the workspace.

create table if not exists public."test" (
  "user_id" uuid not null,
  "id" uuid not null default gen_random_uuid() primary key,
  "name" text,
  "created_at" timestamptz default now()
);

alter table public."test" enable row level security;

drop policy if exists "test_public_read" on public."test";
create policy "test_public_read" on public."test"
  for select
  using (true);

drop policy if exists "test_select_own" on public."test";
create policy "test_select_own" on public."test"
  for select
  using (auth.uid() = "user_id");

drop policy if exists "test_insert_own" on public."test";
create policy "test_insert_own" on public."test"
  for insert
  with check (auth.uid() = "user_id");

drop policy if exists "test_update_own" on public."test";
create policy "test_update_own" on public."test"
  for update
  using (auth.uid() = "user_id")
  with check (auth.uid() = "user_id");

drop policy if exists "test_delete_own" on public."test";
create policy "test_delete_own" on public."test"
  for delete
  using (auth.uid() = "user_id");
